### ISSUE TITLE
[Treemap] few results less than inserted

### ISSUE THREAD

**Issue by miuxapop** [rawgraphs/raw#209]
Hello,
I've been teaching Information Visualization in Lisbon, and our students are using Raw Graphs for most of their projects. We noticed that when using the Treemap visualization, even though we insert 20 results, for instance, most of the times we got 2 or 3 results less than pasted. 
We have already tried editing by the size of the visualization but still got few results less than expected. Does anybody knows if is this a bug or are we doing something wrong?
Thanks in advance!

![fd1bfc17-7479-43f0-82fe-6ad9c223225c](https://user-images.githubusercontent.com/58144877/77900909-a6e5b200-7276-11ea-8958-40c54ad8dbed.png)

**Comment by mikima** [comment]
HI! can you send us a copy of the used dataset? thanks!

**Comment by miuxapop** [comment]
Sure, @mikima! Here it goes in this spreadsheet: [https://docs.google.com/spreadsheets/d/1d6EjWpx9lQ-bbMuKlXP6qKVoCAqKNQbHN-IHutTFN58/edit?usp=sharing] The content is in the tab called "emoji statistics").

After some tests, I could manage to get the whole pasted content by adding on hierarchy the "emojis" characters and also the description of the emoji.

**Comment by mikima** [comment]
Hi! In RAWGraphs the items in the treemap are defined by the hierarchy, as you pointed out. therefore, if you put "frequency you will get a square for each unique value in that column. If you put the "emojis" column you get the correct result
